@HostAddress = http://localhost:5013/api

GET {{HostAddress}}/Car/GetAllCars
Accept: application/json

###
DELETE {{HostAddress}}/Car/25
Accept: application/json

###
GET {{HostAddress}}/Car/GetAllCars
Accept: application/json
###
GET {{HostAddress}}/Bus/GetAllBuses
Accept: application/json

###
GET {{HostAddress}}/Boat/GetAllBoats
Accept: application/json

###
GET {{HostAddress}}/Vehicle/GetAllVehicles
Accept: application/json

###
GET {{HostAddress}}/Colour/GetAllColours
Accept: application/json


########################
GET {{HostAddress}}/Vehicle/GetAllVehicles
Accept: application/json
###
GET {{HostAddress}}/Vehicle/GetAllVehicleByColour/Siyah
Accept: application/json
###
GET {{HostAddress}}/Car/GetAllCarsByColour/Siyah
Accept: application/json
###
GET {{HostAddress}}/Boat/GetAllBoatsByColour/beyaz
Accept: application/json
###
GET {{HostAddress}}/Bus/GetAllBusesByColour/Kırmızı
Accept: application/json
###
POST {{HostAddress}}/Car/ToggleHeadlight
Content-Type: application/json

{
  "id": 24
}