@HostAddress = http://localhost:5013/api

GET {{HostAddress}}/Car/GetAllCars
Accept: application/json

###
GET {{HostAddress}}/Bus/GetAllBuses
Accept: application/json

###
GET {{HostAddress}}/Boat/GetAllBoats
Accept: application/json

###
GET {{HostAddress}}/Vehicle/GetAllVehicles
Accept: application/json

###
GET {{HostAddress}}/Colour/GetAllColours
Accept: application/json


###
GET {{HostAddress}}/Vehicle/GetAllVehicleByColour/Kırmızı
Accept: application/json
###
GET {{HostAddress}}/Car/GetAllCarsByColour/Siyah
Accept: application/json
###
GET {{HostAddress}}/Boat/GetAllBoatsByColour/Mavi
Accept: application/json
###
GET {{HostAddress}}/Bus/GetAllBusesByColour/Beyaz
Accept: application/json
###
